"""
Django settings for simetric project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '153ug+)ockm0yj)o%d^6apig&w=9_a46liap(-!02-&2&xqr8%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simetric.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

APPEND_SLASH=True

WSGI_APPLICATION = 'simetric.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

def default_conf(env: str, secure_value: str) -> str:
    if env in os.environ:
        return os.environ[env]
    return secure_value


DATABASES = {
    'default': {
        'ENGINE':   default_conf('ETL_DB_ENGINE',   'django.db.backends.mysql'),
        'NAME':     default_conf('ETL_DB_NAME',     'simetric'),
        'USER':     default_conf('ETL_DB_USER',     'simetric'),
        'PASSWORD': default_conf('ETL_DB_PASSWORD', 'simetric'),
        'HOST':     default_conf('ETL_DB_HOST',     '127.0.0.1'),
        'PORT':     default_conf('ETL_DB_PORT',     '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

S3_BUCKET=os.environ['ETL_S3_BUCKET']
REDIS_HOST=os.environ['ETL_REDIS_HOST']
REDIS_PORT=os.environ['ETL_REDIS_PORT']
REDIS_PASSWORD=os.environ['ETL_REDIS_PASSWORD']
REDIS_URL=None #os.environ['ETL_REDIS_URL']
NUM_CPUS=int(os.environ['ETL_NUM_CPUS'])
WORKER_PERFIX=os.environ['ETL_WORKER_PERFIX']
ETL_CHANNEL='transport'
IS_MASTER=os.environ['ETL_IS_MASTER']

if not 'LOADED' in os.environ:
    import etl.pubsub
    os.environ['LOADED'] = 'True'
